services:
    alist:
        image: xhofe/alist:latest
        container_name: alist
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        volumes:
            - ./data:/opt/alist/data
            - /root:/root
        ports:
            - 5244:5244
        restart: unless-stopped