name: nginx
services:
    nginx:
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./certs:/etc/nginx/certs
            - ./html:/usr/share/nginx/html
        image: nginx:latest
