services:
    app:
        image: jc21/nginx-proxy-manager:latest
        container_name: npm
        volumes:
          - ./data:/data
          - ./letsencrypt:/etc/letsencrypt
        ports:
          - 80:80
          - 81:81
          - 443:443
        restart: unless-stopped
